### ISSUE TITLE
unable to run composer install command

### ISSUE THREAD

**Issue by Dip20** [kenjis/codeigniter4-multiple-apps-sample#1]
Hello, i am trying to run composer install after cloning this repo, but it's showing me following problems,

 
 Problem 1
   ` - symfony/deprecation-contracts is locked to version v3.0.1 and an update of this package was not requested.
    - symfony/deprecation-contracts v3.0.1 requires php >=8.0.2 -> your php version (7.4.30) does not satisfy that requirement.` 
 
 Problem 2
    `- symfony/deprecation-contracts v3.0.1 requires php >=8.0.2 -> your php version (7.4.30) does not satisfy that requirement. 
    - fakerphp/faker v1.19.0 requires symfony/deprecation-contracts ^2.2 || ^3.0 -> satisfiable by symfony/deprecation-contracts[v3.0.1].
    - fakerphp/faker is locked to version v1.19.0 and an update of this package was not requested.`

**Comment by kenjis** [comment]
Run `composer update` instead.

**Comment by Dip20** [comment]
Thanks a lot.

**Comment by kenjis** [comment]
PHP 7.4 is too old. I recommend you upgrade to PHP 8.1 or later.
